//! Convenience re-export of multiple traits.
//!
//! This allows a HAL user to conveniently import this module and have all the
//! helper traits already imported.
//! Otherwise the use of peripherals would require the import of the
//! corresponding module and the import of the trait, which connects this HAL
//! to the autogenerated svd2rust API in [crate::pac].

pub use fugit::ExtU32 as _fugit_ExtU32;
pub use fugit::RateExtU32 as _fugit_RateExtU32;

pub use crate::adc::AdcExt as _stm32g4_adc_AdcExt;
pub use crate::can::CanExt as _stm32g4_can_CanExt;
pub use crate::dac::DacExt as _stm32g4_dac_DacExt;
pub use crate::exti::ExtiExt as _stm32g4_exti_ExtiExt;
pub use crate::i2c::I2cExt as _stm32g4_i2c_I2cExt;
pub use crate::pwm::FaultMonitor as _stm32g4_pwm_FaultMonitor;
pub use crate::pwm::PwmAdvExt as _stm32g4_pwm_PwmAdvExt;
pub use crate::pwm::PwmExt as _stm32g4_pwm_PwmExt;
pub use crate::pwm::PwmPinEnable as _stm32g4_pwm_PwmPinEnable;
pub use crate::pwm_input::PwmInputExt as _stm32g4_pwm_in_PwmInputExt;
pub use crate::pwr::PwrExt as _stm32g4_pwr_PwrExt;
pub use crate::qei::QeiExt as _stm32g4_qei_QeiExt;
pub use crate::rcc::RccExt as _stm32g4_rcc_RccExt;
pub use crate::rng::RngCore as _stm32g4_rng_RngCore;
pub use crate::rng::RngExt as _stm32g4_rng_RngExt;
pub use crate::serial::LPUartExt as _stm32g4_serial_LPUartExt;
pub use crate::serial::UartExt as _stm32g4_serial_UartExt;
pub use crate::spi::SpiExt as _stm32g4_spi_SpiExt;
pub use crate::timer::SYSTimerExt as _stm32g4_timer_SYSTimerExt;
pub use crate::timer::TimerExt as _stm32g4_timer_TimerExt;

#[cfg(feature = "rtic")]
pub use crate::rtic::Monotonic as _stm32g4_rtic_Monotonic;
