//! Convenience re-export of multiple traits.
//!
//! This allows a HAL user to conveniently import this module and have all the
//! helper traits already imported.
//! Otherwise the use of peripherals would require the import of the
//! corresponding module and the import of the trait, which connects this HAL
//! to the autogenerated svd2rust API in [crate::pac].

pub use fugit::ExtU32 as _fugit_ExtU32;
pub use fugit::RateExtU32 as _fugit_RateExtU32;

pub use crate::delay::{
    DelayExt as _stm32g4_delay_DelayExt, SYSTDelayExt as _stm32g4_delay_SYSTDelayExt,
};
pub use crate::gpio::GpioExt as _stm32g4_gpio_GpioExt;
pub use crate::pwr::PwrExt as _stm32g4_pwr_PwrExt;
pub use crate::rcc::RccExt as _stm32g4_rcc_RccExt;
