//! Convenience re-export of multiple traits.
//!
//! This allows a HAL user to conveniently import this module and have all the
//! helper traits already imported.
//! Otherwise the use of peripherals would require the import of the
//! corresponding module and the import of the trait, which connects this HAL
//! to the autogenerated svd2rust API in [crate::pac].

pub use fugit::ExtU32 as _fugit_ExtU32;
pub use fugit::RateExtU32 as _fugit_RateExtU32;

pub use crate::pwm::FaultMonitor as _stm32g4_pwm_FaultMonitor;
pub use crate::pwm::PwmAdvExt as _stm32g4_pwm_PwmAdvExt;
pub use crate::pwm::PwmExt as _stm32g4_pwm_PwmExt;
pub use crate::pwm::PwmPinEnable as _stm32g4_pwm_PwmPinEnable;
pub use crate::pwm_input::PwmInputExt as _stm32g4_pwm_in_PwmInputExt;
pub use crate::pwr::PwrExt as _stm32g4_pwr_PwrExt;
pub use crate::rcc::RccExt as _stm32g4_rcc_RccExt;
pub use crate::timer::SYSTimerExt as _stm32g4_timer_SYSTimerExt;
pub use crate::timer::TimerExt as _stm32g4_timer_TimerExt;

#[cfg(feature = "rtic")]
pub use crate::rtic::Monotonic as _stm32g4_rtic_Monotonic;
